### ISSUE TITLE
Offline?

### ISSUE THREAD

**Issue by angelod1as** [ChristianSiegert/panoptikos#34]
Opening the website URL leads to "Problem loading page"

http://panoptikos.com/

**Comment by ChristianSiegert** [comment]
Thanks for raising this issue. The redirect from panoptikos.com to its successor, [popular.pics](https://www.popular.pics), stopped working because the domain registry’s system in charge of the redirect appears to be slow/non-functional. I changed the DNS entries so panoptikos.com redirects to popular.pics properly again.
